services:
  postgres:
    ports:
      - "127.0.0.1:${POSTGRES_LOCAL_PORT:-5432}:5432"

  familychat.sso:
    build:
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "127.0.0.1:${SSO_HTTP_PORT:-8080}:8080"

  nginx:
    ports:
      - "127.0.0.1:${NGINX_LOCAL_PORT:-80}:80"