#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${POSTGRES_APP_DB};
    CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_APP_DB" <<-EOSQL
    GRANT CONNECT ON DATABASE ${POSTGRES_APP_DB} TO ${POSTGRES_APP_USER};
    GRANT USAGE, CREATE ON SCHEMA public TO ${POSTGRES_APP_USER};

    GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
    TO ${POSTGRES_APP_USER};

    GRANT USAGE, SELECT, UPDATE
    ON ALL SEQUENCES IN SCHEMA public
    TO ${POSTGRES_APP_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLES TO ${POSTGRES_APP_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE
    ON SEQUENCES TO ${POSTGRES_APP_USER};
EOSQL